### ISSUE TITLE
youtube_dl.utils.PostProcessingError: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

### ISSUE THREAD

**Issue by dovahkinnn** [imdadahad/automate-youtube-to-mp3-with-python#1]
youtube_dl.utils.PostProcessingError: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
 how to fix windows?

**Comment by IvanSthlm** [comment]
Try this:
https://stackoverflow.com/a/60402088

**Comment by milboro77** [comment]
I got the problem listed below:

`Please enter the YouTube Video URL: https://www.youtube.com/watch?v=qNBNfzPRWQQ
[youtube] qNBNfzPRWQQ: Downloading webpage
ERROR: qNBNfzPRWQQ: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1827, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: qNBNfzPRWQQ: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 31, in <module>
    run()
  File "run.py", line 9, in run
    video_info = youtube_dl.YoutubeDL().extract_info(
  File "C:\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "C:\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: qNBNfzPRWQQ: YouTube said: Unable to extract video data`

**Comment by odunayo12** [comment]
The link suggested by @IvanSthlm would help you install `ffmpeg` on your machine. The app has also been updated.  You can try it out now.
